package com.raven.pojo;

public class Code {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.id
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.xsdcode
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private String xsdcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.used
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private String used;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.name
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.subject
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private String subject;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.id
     *
     * @return the value of t_code.id
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.id
     *
     * @param id the value for t_code.id
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.xsdcode
     *
     * @return the value of t_code.xsdcode
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public String getXsdcode() {
        return xsdcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.xsdcode
     *
     * @param xsdcode the value for t_code.xsdcode
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setXsdcode(String xsdcode) {
        this.xsdcode = xsdcode == null ? null : xsdcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.used
     *
     * @return the value of t_code.used
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public String getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.used
     *
     * @param used the value for t_code.used
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setUsed(String used) {
        this.used = used == null ? null : used.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.name
     *
     * @return the value of t_code.name
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.name
     *
     * @param name the value for t_code.name
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.subject
     *
     * @return the value of t_code.subject
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.subject
     *
     * @param subject the value for t_code.subject
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }
}