package com.raven.pojo;

public class Pay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay.id
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay.payname
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private String payname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay.payamout
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private Double payamout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay.paytime
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private String paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay.paystaus
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private String paystaus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay.mail
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay.auditpass
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private String auditpass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay.xsdcode
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    private Integer xsdcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay.id
     *
     * @return the value of t_pay.id
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay.id
     *
     * @param id the value for t_pay.id
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay.payname
     *
     * @return the value of t_pay.payname
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public String getPayname() {
        return payname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay.payname
     *
     * @param payname the value for t_pay.payname
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setPayname(String payname) {
        this.payname = payname == null ? null : payname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay.payamout
     *
     * @return the value of t_pay.payamout
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public Double getPayamout() {
        return payamout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay.payamout
     *
     * @param payamout the value for t_pay.payamout
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setPayamout(Double payamout) {
        this.payamout = payamout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay.paytime
     *
     * @return the value of t_pay.paytime
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public String getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay.paytime
     *
     * @param paytime the value for t_pay.paytime
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setPaytime(String paytime) {
        this.paytime = paytime == null ? null : paytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay.paystaus
     *
     * @return the value of t_pay.paystaus
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public String getPaystaus() {
        return paystaus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay.paystaus
     *
     * @param paystaus the value for t_pay.paystaus
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setPaystaus(String paystaus) {
        this.paystaus = paystaus == null ? null : paystaus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay.mail
     *
     * @return the value of t_pay.mail
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay.mail
     *
     * @param mail the value for t_pay.mail
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay.auditpass
     *
     * @return the value of t_pay.auditpass
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public String getAuditpass() {
        return auditpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay.auditpass
     *
     * @param auditpass the value for t_pay.auditpass
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setAuditpass(String auditpass) {
        this.auditpass = auditpass == null ? null : auditpass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay.xsdcode
     *
     * @return the value of t_pay.xsdcode
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public Integer getXsdcode() {
        return xsdcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay.xsdcode
     *
     * @param xsdcode the value for t_pay.xsdcode
     *
     * @mbg.generated Fri Mar 22 14:22:36 CST 2015
     */
    public void setXsdcode(Integer xsdcode) {
        this.xsdcode = xsdcode;
    }
}