mybatis:
  mapper-locations: classpath*:com/raven/dao/*.xml
logging:
  level:
    com.raven.dao: debug  
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/codepay?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver